# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "wl" "applesmc" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems = [
    { mountPoint = "/";
      device = "/dev/disk/by-label/nixos";  # /dev/sda8
      fsType = "ext4";
      options = "rw,relatime";
    }
    { mountPoint = "/boot";
      device = "/dev/disk/by-uuid/ACE9-6C8E";  # /dev/sda7
      fsType = "vfat";
      options = "rw,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro,relatime";
    }
    { mountPoint = "/home";
      device = "/dev/disk/by-label/home";  # /dev/sda9
      options = "defaults,relatime";
    }
    { mountPoint = "/home/mail";
      device = "/dev/disk/by-label/mail";
      options = "defaults,relatime";
    }
    { mountPoint = "/tmp";
      device = "tmpfs";
      fsType = "tmpfs";
      options = "nosuid,nodev,relatime";
    }
  ];
  swapDevices = [
    { device = "/dev/disk/by-uuid/fd04895d-5c9d-4b88-8e34-2bd5d41cb698"; }  # /dev/sda11
  ];

}
